openapi: 3.0.3
info:
  title: Aura API
  description: |-
    API for the banking app "Aura".
  version: 0.1 alpha
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://127.0.0.1:8080
tags:
  - name: login
    description: Everything about user connection
  - name: accounts
    description: Access to users' accounts
  - name: transfer
    description: Operations on users' account
paths:
  /login:
    post:
      tags:
        - login
      summary: Logs user into the system
      description: Returns the status of the login
      operationId: login
      requestBody:
        description: the credentials of the user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialsResult'
        'default':
          description: issue with the request
  /accounts/{id}:
    get:
      tags:
        - accounts
      summary: Gets accounts by user id
      description: Returns a list of accounts
      operationId: findAccountsByUserId
      parameters:
        - name: id
          in: path
          description: ID of user to return the accounts
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Account'
        'default':
          description: Issue with the request
  /transfer:
    post:
      tags:
        - transfer
      summary: Does a bank transfer between two users
      description: Return the status of the operation.
      operationId: transfer
      requestBody:
        description: all the information to do the transfer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResult'
        'default':
          description: Invalid tag value
components:
  schemas:
    Credentials:
      type: object
      properties:
        id:
          type: string
          example: "1234"
        password:
          type: string
          example: "p@$$word"
    CredentialsResult:
      type: object
      properties:
        granted:
          type: boolean
          example: true
    Account:
      type: object
      properties:
        id:
          type: string
          example: "1"
        main:
          type: boolean
          example: true
        amount:
          type: number
          example: 2331.31
    Transfer:
      type: object
      properties:
        sender:
          type: string
          example: "1234"
        recipient:
          type: string
          example: "1234"
        amount:
          type: number
          example: 2331.31
    TransferResult:
      type: object
      properties:
        result:
          type: boolean
          example: true